rest-for-physics/framework

examples/multiCoboAnalysis.rml
source/framework/core/inc/TRestProcessRunner.h
source/framework/core/inc/TRestThread.h
source/framework/core/src/TRestProcessRunner.cxx
source/framework/core/src/TRestThread.cxx

This is related to issue #28. Tested to be working on processing pandax data.

output event ids reordering

---

CONTRIBUTING.md
README.md

Minor README and CONTRIBUTION guide updates

Minor updates

---

source/framework/tools/src/TRestReflector.cxx

Somehow the typeinfo becomes null after initializing the reflector from typename if the type has no root dictionary. This causes the seg.fault in the pipeline: 
https://gitlab.cern.ch/rest-for-physics/rawlib/-/jobs/14353889
A refreshing of TRestReflector::typeinfo is added(line 251). Some simplification is also done in the method: TRestReflector::InitDictionary().

Continue fixing bugs for reflector's realtime dictionary generation

---

pull-submodules.py

pull-submodules.py fixing a problem when using --latest in raw mode

---

source/framework/core/inc/TRestMesh.h
source/framework/core/src/TRestMesh.cxx

Simply added a method to be able to recover the energy at a given group nodes id (or cluster).

Minor mesh updates

---

.gitlab-ci.yml
pipeline/pandaxiii_MC/processes_2D.rml

Fixes the pandaxiii pipeline due to the renaming of observables at rest-for-physics/tracklib#5

Fixing pandaxiii pipeline

---

CMakeLists.txt
source/framework/core/inc/TRestMesh.h
source/framework/core/src/TRestMesh.cxx

Changes proposed in this pull-request:
- Added a method to get the average position for a group
- Renamed GetGroupIdEnergy by GetGroupEnergy.

Mesh updates

---

source/framework/core/inc/TRestVersion.h

Updated TRestVersion.h to v2.3.8

---

source/framework/core/inc/TRestVersion.h

Fixes #
Fixes in TRestAnalysisPlot, ref. #99.
Fix a bug in TRestRun when test run if off, and the returned event is NULL from the process. The NULL returned event will not be cloned to the output event, ref #95.
Changes proposed in this pull-request:
rawlib updated to version 1.4.
detectorlib updated to version 1.4.
tracklib updated to version 1.2.
Implemented error notifications at the end of restManager execution, ref #94.
Reminder: New features and upgrades should be sufficiently documented and a corresponding validation test at the pipeline should be implemented.

Release v2.3.9

---

.gitlab-ci.yml

Pipeline/trexdm Removing forking feature to fix the pipeline

---

README.md

Just a quick main README.md revision

Updating main README.md

---

source/framework/tools/inc/TRestPhysics.h

TRestPhysics adding AU and solarRadius constants

---

source/framework/tools/src/TRestReflector.cxx

Trying to solve pipeline at rest-for-physics/rawlib#51

TRestReflector. Updating hot compilation flags

---

source/framework/tools/src/TRestSystemOfUnits.cxx

A minor addon to skip parameters/fields defining elements using {}

TRestSystemOfUnits minor update

---

macros/REST_MakeMetadata.C

REST_MakeMetadata. Adding Getters/Setters. And fixing minor issues

---

macros/REST_MakeMetadata.C
macros/REST_MakeProcess.C

Adding override and const to templates after recent changes in framework

---

.github/workflows/validation.yml

Renaming some artifacts to see if the pipeline issues are fixed.

Try to fix issue of pipeline failing due to artifacts

---

CMakeLists.txt
source/framework/CMakeLists.txt

This PR solves compilation issues at NAF-IAXO

Linking mpfr library fix

---

pipeline/ValidateTrees.C

ValidateTrees.C rounding to 2-decimal digits

---

.github/workflows/validation.yml

This is just a dummy update to try to debug the pipeline

Validation.yml dummy update

---

.github/workflows/validation.yml
.gitlab-ci.yml
pipeline/selection/Validate.C

Should close also PR #310. Connected with rest-for-physics/restG4#72.

Fixing pipelines

---

.gitmodules

New library has been added for the calculation of different wimp parameters and sensitivity prospects.
Please, check https://github.com/rest-for-physics/wimplib for more details

Adding new library wimplib

---

CMakeLists.txt

CMakeLists.txt requiring minimum ROOT version 6.24

---

.github/workflows/validation.yml

Pipeline is failing due to custom pipeline after https://github.com/rest-for-physics/framework/pull/371, adding master branch to fix the pipeline issue
Related PR:
https://github.com/rest-for-physics/rawlib/pull/99
https://github.com/rest-for-physics/axionlib/pull/51
https://github.com/rest-for-physics/geant4lib/pull/92
https://github.com/rest-for-physics/wimplib/pull/8
https://github.com/rest-for-physics/tracklib/pull/30
https://github.com/rest-for-physics/legacylib/pull/6
https://github.com/rest-for-physics/connectorslib/pull/26
https://github.com/rest-for-physics/detectorlib/pull/70

Replacing custom branch pipeline by master

---

cmake/LibraryVersion.cmake
source/CMakeLists.txt

- Closes https://github.com/rest-for-physics/framework/issues/449

Add macro to find library version from git

---

doc/tutorials/List of REST Processes.md
macros/REST_DataSummary.C
pipeline/trex/01_raw.rml
pipeline/trex/02_signal.rml
pipeline/trex/03_hits.rml
pipeline/trex/globals.xml
pipeline/trex/run.xml
source/framework/core/inc/TRestEvent.h
source/framework/core/inc/TRestHits.h
source/framework/core/src/TRestHits.cxx
source/framework/core/src/TRestMetadataPlot.cxx
source/framework/core/src/TRestVolumeHits.cxx
source/framework/core/src/startup.cpp

Add method to explicitly compute total energy instead of trusting the pre-computed variable.

Compute hits energy

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/docs.yml
README.md

Documentation gets automatically built and pushed on each push to master.
After merging this PR it will be accessible at https://rest-for-physics.github.io/framework/

Automated Doxygen documentation

---

.github/CODEOWNERS
.github/workflows/validation.yml

Minor fixes

---

source/framework/core/inc/TRestMetadata.h
source/framework/core/src/TRestMetadata.cxx

Helper method to retrieve version components

---

source/framework/core/inc/TRestRun.h
source/framework/core/src/TRestProcessRunner.cxx

- https://github.com/rest-for-physics/rawlib/pull/139

Show progress bar on feminos-daq

---

projects/README.md
source/framework/core/src/TRestEveEventViewer.cxx

Flip projection in viewer so we look at events from the front as if the viewer was in positive Z looking into origin.

Flip XY projection in viewer
