rest-for-physics/framework

- README.md
- pull-submodules.py
A simple patch at `pull-submodules.py` so that we are allowed to specify submodules that should be ignored trhough the command line.
I.e. the following command will avoid pulling geant4lib, restG4 and axionlib.
```
python3 pull-submodules.py --exclude:geant4lib,restG4,axionlib
```
In principle, it will also apply to submodules from submodules. So the following command will pull `axionlib` excluding the internal submodule `SolarAxionFlux` which contains big size data.
```
python3 pull-submodules.py --exclude:solarAxionFlux
```
> Pull submodules exclude

- scripts/checkoutRemoteBranch.sh
I added a script that will allow us to checkout a remote branch if it exists, if it does not exist it will just checkout the `master` branch.
This can be used at libraries pipelines so that when we name the branch at `geant4lib` and `restG4` using the same name, the pipeline will test one against the other.
I.e. if `restG4` is validating branch `bbxx`, it will attempt to pull branch `bbxx` from `geant4lib` if it exists.
> Checkout bash script

- source/bin/restManager.cxx
This fixes a problem when reading `restManager` with several `--f` arguments, such as `restManager --f xx.root --f yy.root --f zz.root`.
There was a bug and it would just catch the latest input file.
> Rest manager fix

- .gitlab-ci.yml
- pull-submodules.py
I have modified `pull-submodules.py` so that when the `--latest` argument is present, it will pull the `master` branch of each submodule by default, except if a branch with the same name as in the `framework` is found at that submodule.
That enables me to check the framework pipeline at this particular branch, while applying changes at a submodule branch with the same name, i.e. `revert_rawsignal`, thats PR rest-for-physics/rawlib#21.
> Validating the framework against a specific submodule branch

- CMakeLists.txt
The goal of this PR is to make REST compatible with C++17 (and not break anything in between).
I just updated the CMakeLists.txt file to set the CXX standard dynamically to match the one used to compiled ROOT.
I tried to do this using REGEX which are implemented in CMake but I failed, its not very well documented. Added TODO to the file.
```
```
Looks like this is enough to allow building REST with C++17 if ROOT was also built using C++17.
> CMakeLists.txt update (compatibility with C++17)

- source/framework/core/src/startup.cpp
This is a quick fix related to issue #76
Now TRestReflector::ToString() converts double/float to string with the same precision as we set for cout.
```
root [0] cout<<M_PI<<endl;
3.14159
root [1] any(M_PI).ToString()
(std::string) "3.14159"
root [2] cout.precision(16)
(long) 6
root [3] cout<<M_PI<<endl;
3.141592653589793
root [4] any(M_PI).ToString()
(std::string) "3.141592653589793"
```
> TRestReflector::ToString() for basic types now read cout precision

- CMakeLists.txt
Changes proposed in this pull-request:
- Remove the 777 permissons at REST_PATH by 755. That should be enough
> Removed permissons for others at REST_PATH

- source/framework/core/inc/TRestEventProcess.h
Now mathematical expressions are also evaluated
Even if not yet merged to master, this commit was tagged as v2.3.8 and it belongs to release v2.3.8.
Notice that the tag is not connected with master, and the best way to download the tag is `git checkout tags/v2.3.8`
> TRestEventProcess::InitFromConfigFile. 

- source/framework/core/inc/TRestThread.h
- source/framework/core/src/TRestThread.cxx
Fix a bug when test run if off, and the returned event is NULL from the process. The NULL returned event will not be cloned to the output event.
> Nkx111 testrunfix

- source/bin/restManager.cxx
- source/framework/core/inc/TRestMetadata.h
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestMetadata.cxx
- source/framework/core/src/TRestProcessRunner.cxx
- source/framework/core/src/TRestRun.cxx
- source/framework/core/src/TRestThread.cxx
- source/framework/core/src/startup.cpp
- source/framework/tools/inc/TRestStringOutput.h
- source/framework/tools/src/TRestStringOutput.cxx
I am trying to create error notifications at the end of `restManager` execution. The idea behind is that we get a list of errors of processes or metadata structures that invoked `TRestMetadata::SetError`.
I thought implementing it at the end of `TRestProcessRunner::ConfigOutputFile()` would do the job. But it seems that only metadata classes directly added to `TRestRun` are available. But no processes.
For example, I added at the detector lib some notifications, 
https://github.com/rest-for-physics/detectorlib/pull/14
I added it for both the process and gas metadata, but only gas metadata error comes out. 
This is an example when I compile REST without Garfield, but I try to use `TRestDetectorGas`.
> Error notifications

- .gitlab-ci.yml
- pipeline/analysisPlot/ValidateClassify.C
- pipeline/analysisPlot/classify.rml
- source/framework/core/src/TRestAnalysisPlot.cxx
Changes proposed in this pull-request:
- A fix when using a full-path filename at `save=""`.
- A fix when getting run info.
- A new validation for analysisPlot when using `classify fRunNumber=`.
I identified a problem on `TRestAnalysisPlot::GetRunInfo`. In some circumstances the run number for the corresponding file was not being properly retrieved. It seems that `GetRunInfo` optimises the opening/closing of files, in case the `fRun` is already open, however, there were some problems. The fix I introduced is bypassing that optimisation and opening the file each time this method is called.
Of course, this is not the best, but as it is right now it works, and I added a new validation test for analysisPlot to check this problem.
If these lines are removed,
```
571 …
```
> Analysis plot fix

- source/framework/core/inc/TRestEveEventViewer.h
- At #44 it was updated the GEOM_SCALE from 0.1 to 1 for ROOT versions above 6.24. However, I am using ROOT 6.20 and the hits did not appear at the right position inside the geometrical volumes. Applying this PR update fixes the problem for me.
Not sure if the problem could be connected with the fact that I generated the data in sultan using ROOT 6.24, and then visualised on my local PC with ROOT 6.20.
> TRestEveEventViewer. GEOM_SCALE is set to 1 for any ROOT version

- .gitlab-ci.yml
Just adds an increased time for data files to be produced at TREX-DM data validation.
> Pipeline debugging

- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestRun.cxx
> TRestRun::OpenInputFile. Fixing a problem on runTag extraction

- pipeline/metadata/readout/PrintReadout.C
- source/framework/core/inc/TRestMetadata.h
It will cause double free problems if we use `=` or copy constructor for metadata classes. The reason is that the data member `fElement` as a pointer will also be copied. And when we delete the two metadata classes, the same pointer will be deleted twice. For example:
```cpp
TRestDetectorGas *g=new TRestDetectorGas("server","Xenon-TMA 0.1Pct 10-10E3Vcm") // initialize a metadata
{TRestDetectorGas gg = *g;} // make a new copy and delete.
delete g;  // this delete operation will cause seg.fault
```
In this PR I undefined the `=` operator. Now the second line doesn't work, and avoids this problem.
Now to copy metadata or to use the object(instead of pointer), one can use `Clone()`, or reference:
```cpp
TRestDetectorGas* g=new TRestDetectorGas("server","Xenon-TMA 0.1Pct 10-10E3Vcm") …
```
> TRestMetadata: undefine = operator method overload

- source/framework/core/src/TRestHits.cxx
- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestSystemOfUnits.cxx
- source/framework/tools/src/TRestTools.cxx
Adds two new methods at TRestTools, `ChangeDirectory` and `ReturnToPreviousDirectory`.
Those were implemented in order to be used at `restG4`. rest-for-physics/restG4#27
> Change directory

- source/framework/core/src/TRestRun.cxx
- Added protection against segmentation fault.
> TRestRun::GetRunInformation. Protecting method

- source/framework/core/inc/TRestAnalysisPlot.h
- source/framework/core/src/TRestAnalysisPlot.cxx
Now we can define histo color/line/file styles with directly string in TRestAnalysisPlot. Previously we must input enum values of each item. The supported styles were defined in Rtypes.h, TAttLine.h and TAttFill.h respectivelly. (In rml these names shall be converted according to our standard parameter-datamember logic. e.g., kYellow --> yellow, kFullDotLarge --> fullDotLarge)
Now we can use 
```
<plot name="Energy" title="Energy spectrum" xlabel="Energy [keV]" ylabel="Counts" value="ON" stats="ON" >
<histo name="1MeV_5um" fillColor="red" lineColor="red">
<variable name="sAna_ThresholdIntegral" range="(0,200e3)" nbins="100"/>
<classify runTag="1MeV_5um"/>
</histo>
<histo name="5MeV_5um" fillColor="gray" lineColor="blue">
<variable name="sAna_ThresholdIntegral" range="(0,200e3)" …
```
> TRestAnalysisPlot supports color/line/fill style def with strings

- source/framework/core/inc/TRestCut.h
- source/framework/core/src/TRestCut.cxx
Added new class: TRestCut. A metadata class which collects TCut objects initialized from rml, e.g:
```xml
<TRestCut/>
<cut name="cc1" value="XX>10 AND XX<90"/>
<cut name="cc2" value="sAna_ThresholdIntegral<100e3"/>
</TRestCut>
```
The notations " AND " and " OR " will be replaced by " && " and " || " .
When saved to ROOT file, this class will save together all its TCut objects 
When we open the output file, we can easily draw histogram with different cuts, to investugate their impacts.
```
AnalysisTree->Draw("xxx",*cc1)
AnalysisTree->Draw("xxx",*cc1 && *cc2 )
```
By properly defing TCuts it also tells other people how to select events.
```
KEY: TCut     fiducial;1        pHitsAna_MeanX>120 && pHitsAna_MeanX<280 && pHitsAna_MeanY>-180 && pHitsAna_MeanY<-20
KEY: TCut     cs137;1 …
```
> New class: TRestCut

- cmake/FindROOT.cmake
Related to #133.
While helping @jovoy, we stumbled over the `FindROOT.cmake` script which currently:
- neither checks whether `ROOTSYS` is defined (i.e. whether `thisroot.*` was sourced)
- nor just uses the `root-config` to get all information it needs.
So this PR:
- throws a fatal error on Windows in case `ROOTSYS` is undefined
- uses the result of `root-config --bindir` on unix, as that is all we need to determine the path to `rootcint`.
I'm neither a cmake expert, nor sure whether it's wise in the first place to continue if `ROOTSYS` is not defined. I can't foresee if later not having sourced the file leads to even harder to debug issues. Alternatively, we could also just check for the existence of the variable on unix and fatal error in the same way.
If `FindROOT.cmake` is buried …
> Fix `FindROOT.cmake` in case `thisroot.sh` wasn't sourced

- source/framework/core/src/TRestProcessRunner.cxx
- source/framework/core/src/TRestRun.cxx
fix a bug that when manually quit the file process from pause menu, the `EndProcess()` method of external process is not called.
> fixed calling of external process's endprocess() method

- cmake/scripts/RESTConfig.cmake
- cmake/thisREST.cmake
Changes to the CMake files to support inclusion of REST via `find_package(REST)`.
Added new command: `rest-config --prefix` which returns the installation path of REST (doesn't have to be the same as the current REST_PATH).
When doing `find_package(REST)` it will check that the current REST_PATH and the installation path of REST match. It will throw an error if they don't.
> Updated CMake for inclusion of REST via find_package

- cmake/FindGarfieldOld.cmake
CMakeLists fixes related to Garfield compilation of old versions.
Related to rest-for-physics/framework#37
> Garfield compilation fix

- source/framework/core/inc/TRestEventProcess.h
A simple PR to make `TRestEventProcess::Begin/EndOfEventProcess` virtual so that they can be re-implemented at the inherited classes.
This is required by rest-for-physics/axionlib#12
> TRestEventProcess::Begin/EndOfEventProcess are now virtual

- .gitlab-ci.yml
- CMakeLists.txt
- source/framework/core/src/TRestMetadata.cxx
- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestTools.cxx
- It adds dependency with libcurl libraries
- It adds a static method `TRestTools::POSTRequest` to do POST requests to a website.
- `TRestTools::ReadASCIITable` added an optional argument to skip header lines.
- `TRestMetadata::GetSearchPath` now adds also `REST_USER_PATH` as a default.
- `TRestTools::ExportASCIITable` method added to write a file with the contents of `std::vector<std::vector>>`.
> It adds a method at TRestTools to do http POST requests

- source/framework/core/inc/TRestVolumeHits.h
After new changes in the code, it seems that root doesn't like `override` method, see below:
Fix this error by removing `override` from `TRestVolumeHits`
> Removing override, looks problematic with root

- source/framework/tools/src/TRestTools.cxx
Fixing a problem when no CURL libraries are present.
> TRestTools. Adding forgotten USE_Curl encapsulation

- .gitlab-ci.yml
- cmake/Testing.cmake
- cmake/thisREST.cmake
- pipeline/pandaxiii_MC/Xe136bb0n.rml
- pipeline/pandaxiii_MC/geometry/Th232_SS_01.rml
- source/framework/core/inc/TRestGDMLParser.h
- source/framework/core/src/TRestGDMLParser.cxx
- source/framework/core/src/TRestMetadata.cxx
- source/framework/test/src/FrameworkCore.cxx
- source/framework/tools/src/TRestStringHelper.cxx
* Related to https://github.com/rest-for-physics/restG4/issues/43
* Replaces Nevents by nEvents in RML files (Nevents still works) for consistency
* Replaces gdml_file by gdmlFile in RML files (gdml_file still works) for consistency
TRestGDMLParser:
* Renamed members for consistency (starting with `f`...)
* Made some methods parameters by const ref.
* When USER is not defined, will save temporary gdml file to `/tmp` directory instead of failing
* Includes <filesystem> header to create directory recursively if not exists
* Other minor changes
> Minor updates for TRestGDMLParser

- CMakeLists.txt
- cmake/GitHooks.cmake
- cmake/utils/git_pre-commit.in
- scripts/reformat-clang.sh
- source/framework/CMakeLists.txt
Script `reformat-clang` has been improved:
- Added `readlink` to make the script independent from the path where is launched
- Adding support for single files including file extensions `*.h`, `*.cxx`, `*.cc` and `*.C`
- Now the script check if the file or directory exists
- Removing un-necessary commands
**Added  `githook` in the `cmake`, so the `clang-format` is performed when `git commit` is issued**
- `githook` is created when `cmake` is issued and if there is no `pre-commit` present.
- Check if `clang-format` is present in the system, otherwise is skipped.
- Can be used as template to add different `githook` features.
> Improving clang formatting

- source/bin/restRoot.cxx
- source/framework/CMakeLists.txt
- source/framework/core/src/TRestMetadata.cxx
- source/framework/core/src/TRestRun.cxx
This PR adds the following minor changes:
- `restRoot` now will warn the user if we use `restRoot file.root` and `file.root` does not exist.
- `TRestRun::ReadFileInfo` bug fixed.
- `TRestMetadata::GetSearchPath`. Added `REST_PATH/examples` directory to the default search paths.
- `framework/CMakeList` fixed a compilation issue related to `std::filesystem`
> Minor but urgent fixes

- CMakeLists.txt
Adding requirement for `C++17` in the `CMakeLists`:
- After checking `ROOT` compilation `C++` standard, a requirement for `C++17` has been added. Note that new structure bindings have been implemented in the code, which requires `C++17` standard.
> Adding requirement for C++17

- CMakeLists.txt
I found out that I need to add this fix in order to be able to compile at sultan2, strange ... but
> CMakeLists.txt adding std++fs linking

- source/framework/core/src/startup.cpp
Potential fix for #169 
- Now `REST_PATH` is not set in case of testing are enabled. I checked that is working fine with the test currently implemented, however we might have potential issues in case `REST_PATH` is required. However, `REST_PATH` cannot be set during test since installation path is not present at this stage...
- Doesn't change the logic when test are disabled.
- Added new`RESTError` and `RESTWarning` functions instead of `std::cout`
> Work around to avoid return when test are enabled

- cmake/GitHooks.cmake
Found in https://github.com/rest-for-physics/geant4lib/pull/50#issuecomment-1137076035 that pre-commit hooks are not working for submodules in case cmake was performed between these 2 PR:
- https://github.com/rest-for-physics/framework/pull/203
- https://github.com/rest-for-physics/framework/pull/208
Now the existence of the `pre-commit` submodule `hook` is checked every time, independenty of the `pre-commmit` present in `framework`
> Fix potential issue in pre-commit submodule hooks

- source/framework/core/src/TRestGDMLParser.cxx
- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestTools.cxx
Before C++17 we had to do some complicated logic to work with paths, this is solved with the `<filesystem> header, now present at REST.
Some methods to work with paths in REST relied on environment variables to work, such as `PWD`. This was causing some unexpected issues on my dev environment when the `PWD` env variable doesn't match the current working directory.
I have removed all apperances of environment variables when working on paths and I have rewritten the old methods to use `<filesystem>`. Now these methods are a single line and could probably be removed altogether so people start using the filesystem library, but they remain for now.
I removed the method `TRestTools::ReturnToPreviousDirectory` as it relied on environment variables for state management and it was only used once …
> Simplified some of TRestTools methods using `<filesystem>` and avoid usage of env variables

- .gitlab-ci.yml
- .gitmodules
- scripts/reformat-files.sh
- source/framework/core/src/TRestRun.cxx
- source/framework/tools/inc/TRestStringHelper.h
- source/framework/tools/src/TRestStringHelper.cxx
New `legacy` library has been added to the repository, check https://github.com/rest-for-physics/legacylib for more details.
The new  `legacy` library is meant to store deprecated libraries in order to keep backward compatibility of the data with the following conditions:
- A `legacy` class can be instanciated, in this case a warning in displayed.
- A `legacy` class doesn't implement any function e.g. "ProcessEvent", an error is displayed and the program exit in case.
- A `legacy` class is capable to print any metadata.
- All  `legacy` classes inherits from `TRestLegacyProcess`, which ensure the proper handling of legacy classes.
For the time being only `TRestRawZeroSuppresionProcess.h` is implemented as legacy class, however more classes can be added following this template. A base class …
> Adding new library legacylib

- source/framework/core/src/startup.cpp
Currently if the `USER` environment variable is not set, `defaultUser` is set as `USER`.
This PR makes use of `whoami` (which also exists on windows apparently) to get the current username, which is not always present in the environtment variable. The `USER` env variable will still take precendence.
If for some reason `whoami` is not found, it will still use `defaultUser` and it won't raise an exception.
> Using `whoami` when USER is not defined instead of default user

- CMakeLists.txt
Closes https://github.com/rest-for-physics/framework/issues/236
> Fixes installation issue in CMake > 3.21

- pull-submodules.py
I think we had to add the following patch in order to get the latest remote. If not, the local master branch was not always synced. Recently remarked by @KonradAltenmueller
> pull-submodules.py minor update

- .github/actions/build/action.yml
- .github/workflows/Validation.yml
- scripts/checkoutRemoteBranch.sh
Implemented github pipeline, by replicating gitlab pipeline. Some modifications wrt gitlab pipeline have been implemented:
- Build is performed using  [build/action.yml](https://github.com/rest-for-physics/framework/blob/12aa266f5cf607a2e86d23412c4aa85983c33350/.github/actions/build/action.yml), three different builds are performed:
- Build: Standard build using docker `ghcr.io/lobis/root-geant4-garfield:rest-for-physics-dev` with G4 version `11.0.2`
- BuildTest: Build with `-DTEST=ON` using docker `ghcr.io/lobis/root-geant4-garfield:rest-for-physics-dev`, after the build `ctest` are performed
- BuildOld: Standard build using docker `ghcr.io/lobis/root-geant4-garfield:rest-for-physics-reference-jun2022` with G4 version  `10.4.3`
- The different validation pipelines have been reshufle …
> Github pipeline

- cmake/thisREST.cmake
Currently `thisREST.sh` script does not source the root or Geant4 installations if they are installed under `/usr`. I don't understand why though, any explanation would be welcome.
I have removed this since the current docker image used for CI has dependencies installed in that directory and github actions pipeline are failing because of this.
> updated thisREST script to work when root/Geant4 is installed in `/usr`

- .gitlab-ci.yml
- source/framework/core/src/TRestAnalysisPlot.cxx
This is to allow `addFile` definitions inside `TRestAnalysisPlot` as `<addFile name="/path/to/file/Run*.root" />`
> TRestAnalysisPlot. Now addFile supports filename patterns

- source/framework/tools/src/TRestTools.cxx
This PR is needed so that libraries generated for packages (required for testing) are not loaded by `restRoot`.
I also replaced substring checking using `std::string` by `TString` since it provides more features which makes the code more readable (in my opinion).
> TRestTools::LoadRESTLibrary - Added possibility to ignore libraries

- .github/workflows/validation.yml
- .gitlab-ci.yml
CI image was updated to `rest-for-physics-dev` in some parts of the pipeline / repositories due to compatibility problems, but it can now be unified with `rest-for-physics`.
The old `rest-for-physics` image (at the time of writing this PR) can be found under `rest-for-physics-reference-jun2022` tag.
Related PR:
* https://github.com/rest-for-physics/restG4/pull/59
> Updated validation image tag to `rest-for-physics`

- source/framework/core/inc/TRestEvent.h
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestEvent.cxx
This PR adds a pointer to `TRestRun` to `TRestEvent` which is initialized when retrieving the event via `TRestRun::GetEntry`. This allows `TRestEvent` to access its corresponding metadata which can be used to improve print methods output for example.
https://github.com/rest-for-physics/geant4lib/pull/56 makes use of this PR.
> Added a pointer to TRestRun in TRestEvent

- pipeline/validateProcesses.py
update validateProcesses.py to fix pipeline
fixes two problems during process validation:
1. when asymmetric brakets in comment
2. when lambda functions in main function
> update validateProcesses.py to fix pipeline

- source/framework/core/inc/TRestAnalysisPlot.h
- source/framework/core/inc/TRestMetadata.h
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestAnalysisPlot.cxx
- source/framework/core/src/TRestEventProcess.cxx
- source/framework/core/src/TRestMetadata.cxx
- source/framework/core/src/TRestRun.cxx
- source/framework/tools/inc/TRestStringHelper.h
- source/framework/tools/src/TRestStringHelper.cxx
- `TRestAnalysisPlot`:
-  Panel labels now allow to define a number precision. i.e. using `<panel font_size="0.4" precision="4" >` will allow for 4-digits after the "." in a float number.
- Now the histogram `<histo` will allow an additional parameter `weight` that will use  a branch to weight the filling of the histogram. This effect could be achieved previously by defining manually the `cutString` definition. Now, however we can do: `<histo name="hName" weight="efficiency" />` where `efficiency` is a branch existing in the tree.
- Modified methods are `TRestMetadata::GetDataMemberValues` and `TRestRun::ReplaceMetadataMember/s`. The default precision is 0 (i.e. the method will work as it was doing before).
- `REST_StringHelper::ReplaceMathematicalExpressions`  will allow to include a …
> Few string and TRestAnalysisPlot enhancements

- source/framework/tools/src/TRestTools.cxx
Some times if we invoke `restRoot` with a macro in the command line that takes as argument a `.root` file, it will interpret that it is a file and not a macro. The problem was not really bad, but it was generating an unnecessary warning telling that the file was not found.
The problem was solved by improving `TRestTools::IsRootFile` method.
> TRestTools::isRootFile improving filename extension identification

- pipeline/validateProcesses.py
The `validateProcesses.py` is failing on the pipeline validation: rest-for-physics/axionlib#12
The problem is that the keyword `ProcessEvent` appears in the documentation of `TRestAxionEventProcess` but in reality there is no `::ProcessEvent` implementation. I added a more strict method search inside the script.
> validateProcesses.py adding a quick fix while searching ProcessEvent method

- source/framework/tools/inc/TRestPhysics.h
- source/framework/tools/src/TRestPhysics.cxx
Adding the interaction between a vector and a parabolic/hyperbolic shaped mirror:
> TRestPhysics.h added parabolic/hyperbolic interaction

- source/bin/restRoot.cxx
Fixes https://github.com/rest-for-physics/framework/issues/282.
Some warnings are now visible that should be addressed in a different PR.
> Fix macros from libraries not loading correctly

- source/framework/core/src/TRestMetadata.cxx
- source/framework/tools/inc/TRestStringHelper.h
- source/framework/tools/src/TRestStringHelper.cxx
Before this PR all `TRestMetadata` classes were using `defaultName` and `defaultTitle` for the default value of said parameters. This was causing an issue when multiple metadata classes were left with the default name values, as the name needs to be unique in the root file.
This PR updates the name of these parameters so that it depends on the class name (`defaultName` -> `defaultTRestGeant4Metadata` etc.). This way if the metadata classes are unique in the root file there won't be a problem even if they are not explicitly named (such is the case in `restG4` simulations).
I also updated the `REST_StringHelper::StringToBool` to also support `std::to_string(true)` as argument and normalized the usage of `std::` in the source file.
I had to add 5e78026dc0b8dd21b4d7b594305bd37d39d23bf5 to fix …
> Update TRestMetadata classes default title and name

- source/framework/tools/inc/TRestSystemOfUnits.h
Adding `arcmin` and `arcsec` units.
> New angle units

- .github/workflows/validation.yml
- .gitlab-ci.yml
- source/framework/core/src/TRestRun.cxx
- source/framework/tools/inc/TRestReflector.h
This reverts commit 050d3bc29d904ca8807772739c700de6d3016af3.
This should fix rest-for-physics/rawlib#74
> Revert "fixed reading of REST v2.2 files"

- source/framework/core/src/TRestRun.cxx
A minor patch to avoid having to manually call to `GetEntry` to fill the new event pointer. It will just fill using the current entry.
> TRestRun::SetInputEvent now updates the content inside the new event

- source/framework/core/inc/TRestAnalysisTree.h
- source/framework/core/inc/TRestEventProcess.h
- source/framework/core/src/TRestAnalysisTree.cxx
This closes issue https://github.com/rest-for-physics/detectorlib/issues/47
By making TRestAnalysisTree::GetObservableValue<>() **searching** for observables, one can directly input obs names without process name prefix. It also prints message if one input observable names wrong.
Previously: 
```
root [1] ana_tree0->GetObservableValue<double>("sAna_ThresholdIntegral")
(double) 161060.00
```
Now:
```
root [0] ana_tree0->GetObservableValue<double>("ThresholdIntegral")
TRestAnalysisTree::GetObservableID(): Find observable sAna_ThresholdIntegral for obs name: ThresholdIntegral
(double) 161060.00
root [2] ana_tree0->GetObservableValue<double>("ThresholdIntegrawwl")
-- Error : TRestAnalysisTree::GetObservableID(): No Matching observable found
-- Error : did you mean "sAna_ThresholdIntegral" ? …
```
> GetObservableValue input obs name without process name prefix

- source/framework/analysis/inc/TRestEventRateAnalysisProcess.h
- source/framework/tools/src/TRestTools.cxx
> Fixing restG4 pipeline!

- source/framework/core/src/TRestProcessRunner.cxx
- source/framework/core/src/TRestRun.cxx
Changed all the occurences of `kWriteDelete` for `kOverwrite`.
This avoids having random numbers after keys in the root file, such as:
```
root [1] .ls
TFile**         /tmp/tmp.NR4gQ6jbwZ/source/packages/restG4/examples/04.MuonScan/muons.root
TFile*         /tmp/tmp.NR4gQ6jbwZ/source/packages/restG4/examples/04.MuonScan/muons.root
KEY: TRestAnalysisTree        AnalysisTree;4  AnalysisTree
KEY: TTree    EventTree;4     TRestGeant4EventTree
KEY: TRestRun CosmicMuonRun;4 A basic muon test with 2 active volumes
KEY: TRestGeant4Metadata      restG4 run;3    MuonsFromWall
KEY: TRestGeant4PhysicsLists  default;3       First physics list implementation.
KEY: TGeoManager      Geometry;1      Geometry imported from GDML
```
Not sure if there was a reason to use `kWriteDelete` in the first place …
> Writing objects with `kOverwrite` flag instead of `kWriteDelete`

- source/framework/tools/src/TRestTools.cxx
Recently `TRestTools` was mofidied (https://github.com/rest-for-physics/framework/pull/295) to fix an error on the GitLab pipeline. The fix removed the case insensitive flag for the comparison of the ignored libraries (since we didn't remember why it was there in the first place) but this breaks the ignore of `restG4` library.
The library is being loaded (altought it doesn't seem to cause any issue, just a warning).
This is because the library name contains `RestG4`, not `restG4`. This name is generated from the package name (`restG4`) which is hardcoded into `TRestTools`. We could just use `RestG4` instead of `restG4` but I think we should instead use the case insensitive comparison so in the future if we can get all the package names automatically instead of hardcoding this will work …
> Fix not ignoring `restG4` library on `restRoot`

- pull-submodules.py
> pull-submodules.py adding an option to download data

- .github/workflows/validation.yml
- .gitlab-ci.yml
- CMakeLists.txt
- source/framework/CMakeLists.txt
This PR clarified some optional dependencies for the framework: `curl`, `mpfr`, `mySQL`, and `ROOT eve library`. Those items will contribute to "REST Features" output when configuring cmake:
```
...
REST will be installed in: xxxx
===========================================================
System is: Linux
Packages: restG4 
Libraries: RestFramework;RestConnectors;RestDetector;RestGeant4;RestLegacy;RestRaw;RestTrack
Features: Eve;CURL,Garfield
===========================================================
```
**mpfr library is made optional**. A new cmake flag is introduced. By setting `-DREST_MPFR=OFF` one can exclude the compilation of the class `TRestComplex`. By default mpfr is OFF.
curl library finding is moved to main CMakeLists.
> update main CMakeLists to set mpfr optional

- source/framework/core/inc/TRestEventProcess.h
- source/framework/masks/inc/TRestPatternMask.h
- source/framework/masks/src/TRestGridMask.cxx
- source/framework/masks/src/TRestPatternMask.cxx
- source/framework/masks/src/TRestRingsMask.cxx
- source/framework/masks/src/TRestSpiderMask.cxx
- source/framework/masks/src/TRestStrippedMask.cxx
- source/framework/tools/inc/TRestSystemOfUnits.h
`TRestPatternMask` defines common members for any `TRestPatternMask`. `TRestPatternMask` was pure virtual so in order to use one had to chose a particular pattern (Grid/Stripped/../Combined).
Now it is also possible to do not define a pattern, and thus there will be no pattern, the only selection will be the limits of the pattern defined by `fMaxRadius` and `fOffset`.
> TRestPatternMask is not pure virtual anymore

- .github/workflows/validation.yml
- .gitlab-ci.yml
- pipeline/selection/Validate.C
It requires to be merged to fix pipelines after updates to use the official materials repository.
It will be merged before tagging the official release v2.3.13.
> Fixing GitLab pipeline

- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestTools.cxx
Now `TRestTools::ReadASCIITable` allows to specify the separator, so that now we are able to read `csv` files by indicating the `comma` separator.
I.e.
```
std::vector<std::vector <Double_t> > d;
TRestTools::ReadASCIITable("myFile.csv", d, 0, "," );
```
Then, the table values will be loaded inside the `d` vector.
> TRestTools::ReadASCIITable upgraded to allow csv files reading

- macros/REST_GenerateResponseMatrix.C
- macros/REST_ListMacros.C
- source/framework/tools/src/TRestTools.cxx
The following macro will allow to generate binary tables from a `TH2D` that was built using any two analysis tree variables.
The initial motivation is to create binary tables with different gas detector response file mixtures to be used in rest-for-physics/axionlib
I want it to be merged before final v2.3.13 release so that it will be available at the official release at NAF-IAXO. Where I want to produce official Geant4 data to be used for generating the response matrix.
For more info, you may have a look at the `REST_GenerateResponseMatrix` documentation.
The documentation should also appear when executing `restManager ListMacros`.
> Response matrix macro

- source/framework/core/src/TRestRun.cxx
Should close https://github.com/rest-for-physics/restG4/issues/73
Now the check returns a warning instead.
> Do not throw error if TRestRun is opened in a non writeable path

- source/framework/core/inc/TRestAnalysisTree.h
just a quick fix for https://github.com/rest-for-physics/framework/issues/316#event-7584532451
> TRestAnalysisTree: recover GetHistogram() for splitted files

- pull-submodules.py
Added `git submodule foreach` to `pull-submodules.py` script:
- Avoids multiple request to github that might cause issues in unizar firewall
- Speed up the checkout of the submodules
Note that the overall behaviour of `pull-submodules.py` has not been significatively changed, however note that  `git submodule foreach` acts on all the submodules that have been initialized.
> Adding foreach to pull-submodules.py

- cmake/thisREST.cmake
Fixes https://github.com/rest-for-physics/framework/issues/331.
> fix source geant4 from thisREST on zsh shell

- source/framework/core/inc/TRestBrowser.h
- source/framework/core/src/TRestBrowser.cxx
On latest root version (6.26/10) the browser is broken because we are hardcoding the icons path, which has been updated.
I also added icons to some of the buttons so they look better (in my opinion).
> fix browser for newer root versions (6.26./10) and add icons to buttons

- examples/masks.rml
- source/framework/masks/inc/TRestSpiderMask.h
- source/framework/masks/src/TRestSpiderMask.cxx
- A new member `fInternalRegionRadius` has been added to `TRestSpiderMask` to allow the definition of a internal circular region to generate a Tie-fighter like structure.
> Adding an internal circular region inside a spider mask

- source/framework/tools/inc/TRestPhysics.h
- source/framework/tools/src/TRestPhysics.cxx
Speed of light was defined twice
> Remove repeated value for the speed of light

- pull-submodules.py
Bug found, submodules inside libraries or other submodules are not updated this happens under `data` on `axionlib`
Adding `--recursive` after `git foreach` to update submodules inside submodules, note that this shouldn't change the behaviour if the submodules have not been initialized.
> Pull submodules recursively

- source/framework/core/src/TRestProcessRunner.cxx
- source/framework/core/src/TRestRun.cxx
This PR should solve issue #338 
I believe the trick was to add `fOutputFile->Write(0, TObject::kOverwrite)`, this fixes additional entries appearing when using `.ls`.
However, I believe that when opening the file using `restRoot`, since we create a new instance, two versions of the object will appear. One it is the instance of the object, the other is the key stored in file.
In reality this is not a 100% fix. The point is that when we open the file using `restRoot file.root` and then use the `TBrowser` the browser shows a replicated object because one is the `key` and the other is the `pointer`. 
If we just do open it using `TFile` then replicated entries will not appear.
> Fixes replicated backup entries appearing on output file

- source/framework/core/src/TRestAnalysisPlot.cxx
Fixes the error reported at https://rest-forum.unizar.es/t/seg-fault-when-running-in-batch-mode-with-plotting/558
> TRestAnalysisPlot. Fixing conflict between batch and previewPlot

- pipeline/analysisPlot/panel.xml
- source/framework/core/inc/TRestAnalysisPlot.h
- source/framework/core/src/TRestAnalysisPlot.cxx
- source/framework/core/src/TRestAnalysisTree.cxx
- source/framework/core/src/TRestRun.cxx
As the title says we cannot use `<<` or `>>` in the xml (or rml) files if we want it to be valid xml, even though some parsers can tolerate it.
I replaced them by square brackets but any suggestion is welcome.
This issue was discovered when running a tool to check for valid xml files.
> use [[(]]) instead of <<(>>) for analysis plots to correct invalid xml syntax

- CMakeLists.txt
- source/bin/restRoot.cxx
- source/framework/CMakeLists.txt
- source/framework/analysis/src/TRestSummaryProcess.cxx
- source/framework/core/inc/TRestDataSet.h
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestDataSet.cxx
- source/framework/core/src/TRestMetadataPlot.cxx
- source/framework/core/src/TRestRun.cxx
- Introduces a fix at `TRestSummaryProcess::EndProcess`. Entries were not properly retrieved from `fRunInfo`.
- Adding a fix in `TRestDataSet` logic to fix problem with file selection by date.
- `TRestRun::GetSubRunNumber` method added.
- `CMakeLists.txt` fixing a bug where excluding `TRestComplex` was not properly implemented.
> Few minor fixes

- scripts/installation/installGarfield.sh
- scripts/installation/installGeant4.sh
- scripts/installation/installROOT.sh
> Upgrading root installation to root-6.26.10

- scripts/validatePreCommitConfig.py
Now the script will compare files to the branch with the same name as the current working directory branch name in framework if it exists, otherwise it will just use master as before.
This will prevent PR such as https://github.com/rest-for-physics/axionlib/pull/50 to begin as failing.
This PR was triggered by https://github.com/rest-for-physics/framework/pull/375
> Update pre-commit check script to work for auto-updates

- pull-submodules.py
I noticed that some submodules were not properly updated in case some submodule failed to pull or checkout the corresponding branch. This typically happens when one submodule has unstaged changes.
The issue is fixed after appending `|| true` after `git submodule foreach` command.
However, note that the faulty submodule will remain in a bad state unless the changes are staged or removed (e.g. using --force), which I think it was the previous behaviour.
> Addressing bug in pull-submodules

- source/framework/core/inc/TRestCut.h
- source/framework/core/inc/TRestDataSet.h
- source/framework/core/src/TRestCut.cxx
- source/framework/core/src/TRestDataSet.cxx
`TRestCut` now is implemented inside `TRestDataSet` to avoid code duplication.
See https://github.com/rest-for-physics/framework/pull/386 for more details
> Implementing TRestCut inside TRestDataSet

- source/framework/core/inc/TRestAnalysisTree.h
- source/framework/core/src/TRestAnalysisTree.cxx
TRestAnalysisTree::GetObservableAverage. Changing the way average is calculated
Other similar methods `GetObservableMax/Min/RMS` have been updated too
> TRestAnalysisTree fixing observable estimators 

- scripts/installation/installROOT.sh
- Fixing typo in installROOT.sh. 
- Disabling xrootd and upgrading ROOT to 6.28.02
> Updating installROOT.sh

- source/framework/analysis/src/TRestDataSetOdds.cxx
This PR try to address a compilation issue on macOS reported here https://rest-forum.unizar.es/t/macos-compilation-errors-restframework-trestdatasetodds-cxx/582
Note that this compilation failure is related with abug in clang, in which structure bindings are not captured in lambda expressions https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding
> Addressing compilation issue in macOS introduced on TRestDataSetOdds

- cmake/MacroRootDict.cmake
See also the following closed PR: https://github.com/rest-for-physics/framework/pull/356
There was a problem with c++ structure identification for dictionary generation. The cmake macro identifying the `struct` keyword was also identifying the keyword `structure` that appears on the documentation. 
This PR solves the proper streaming of `TRestRawBiPoToSignalProcess` that was not properly storing `MatacqBoard` information.
However, there is an additional problem the cmake macro was only identifying the first `struct` found in the class.
```
#ifdef __ROOTCLING__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedef;
#pragma link C++ class MatacqBoard+;
#pragma link C++ class …
```
> MacroRootDict. Improving the identification of structures for dictionary generation

- .github/workflows/validation.yml
Now `restG4` framework validation is pointing to master branch.
Related PR https://github.com/rest-for-physics/restG4/pull/107
> Update restG4 framework validation to point to master

- macros/REST_GenerateDataSet.C
- macros/REST_GenerateDataSets.C
- source/framework/core/inc/TRestDataSet.h
- source/framework/core/src/TRestDataSet.cxx
- source/framework/core/src/TRestMetadata.cxx
`TRestMetadata::GetDataMemberValues` minor fix on TVector2,3 output component
Before this PR (for the case of TVector2,3), the following output was generated when invoking `GetMetadataMember`.
```
root [7] run0->GetMetadataMember("axionGen::fEnergyRange[0]")
(std::string) "(0.05"
root [8] run0->GetMetadataMember("axionGen::fEnergyRange[1]")
(std::string) "10)"
```
After this PR, parenthesis are removed from the output.
```
root [7] run0->GetMetadataMember("axionGen::fEnergyRange[0]")
(std::string) "0.05"
root [8] run0->GetMetadataMember("axionGen::fEnergyRange[1]")
(std::string) "10"
```
Added also:
- `REST_Generate_DataSets` macro that will allow to export several datasets from a given list of dataset names.
- Added new filter condition `equalsTo` that allows to evaluate numerically if a …
> Fix on TRestMetadata and TRestDataSet add-ons

- source/framework/core/inc/TRestHits.h
- source/framework/core/src/TRestHits.cxx
This PR is required by PR https://github.com/rest-for-physics/detectorlib/pull/82
The hard coded numbers are now arguments of the functions.
> TRestHits: error in gaussian fit is now defined by the user

- source/framework/core/inc/TRestDataSet.h
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestDataSet.cxx
- source/framework/tools/src/TRestStringHelper.cxx
- `TRestRun::ReplaceMetadataMembers`. Now default precision is infinite.
- `TRestDataSet::GetFileSelection` added to TRestDataSet copy method
- `REST_StringHelper::CropWithPrecision` fixing a bug causing problems when the given precision is bigger than the string implicit precision.
> Minor TRestDataSet and TRestRun fixes

- source/framework/tools/src/TRestStringHelper.cxx
REST_StringHelper::isAExpression had a bug.
The method was not properly identifying a expression that starts with minus sign
> REST_StringHelper::isAExpression. Fixing a bug

- source/framework/masks/src/TRestCombinedMask.cxx
- source/framework/masks/src/TRestSpiderMask.cxx
> Masks debugging

- cmake/thisREST.cmake
- macros/REST_OpenInputFile.C
- source/bin/restRoot.cxx
Simplifiying `restRoot` behaviour for opening `TRestRun` and `TRestDataSet`
- Reimplementing TRestAnalysisTree, TRestEvent and metadata objects in a dedicated macro `REST_LoadInputFiles.C`
- Droping support for multiple files, now only one `TRestRun` and/or `TRestDataSet` can be opened (the first one)
- If the file is not a `TRestRun` or a `TRestDataSet` it just use default `root` behaviour using `TRint`
- Now the flag to load macros is just  `--m` instead of `--m 1` since the latest is misleading and error prone.
> Simplifying opening of TRestRun and TRestDataSet files

- source/framework/core/inc/TRestBrowser.h
- source/framework/core/inc/TRestEveEventViewer.h
- source/framework/core/inc/TRestEventViewer.h
- source/framework/core/src/TRestBrowser.cxx
- source/framework/core/src/TRestEveEventViewer.cxx
Now the GEOM_SCALE define has been replaced by a data member at `TRestEventViewer::fGeomScale`. In this way we can update the value of scaling dynamically. The default value is now back to `fGeomScale=0.1`. Recently it was updated in #440. However this has generated problems.
Using the present PR and https://github.com/rest-for-physics/geant4lib/pull/108, and the example `01.NLDBD` I see the event properly placed now with 
```
REST_Geant4_ViewEvent( "file.root");
```
while it is placed outside if I redefine `geomScale` to 1.0.
```
REST_Geant4_ViewEvent( "file.root", 1.0);
```
This is only affecting visualisation
It would be interesting to find out when this is happening, so I added a warning message to encourage users feedback.
> Updating hit positions scaling in Eve scene

- macros/REST_OpenInputFile.C
- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestRun.cxx
- source/framework/tools/src/TRestTools.cxx
Addressing issue #452 
- Adding `TRestEvent` pointer while opening `TRestRun` input file
- Removal of the appending `0` for the global variable names
- Now metadata and input event are added using `gROOT->ProcessLine`
> Adding TRestEvent ptr while opening input file

- source/framework/analysis/inc/TRestMySQLToAnalysisProcess.h
- source/framework/analysis/src/TRestMySQLToAnalysisProcess.cxx
Now the file will be processed even if no SQL database entries matching the run timestamp period are found.
> TRestMySQLToAnalysisProcess will continue even if no DB was found.

- macros/REST_OpenInputFile.C
Fixes an issue opening with `restRoot` when the name contains minus signs.
> REST_OpenInputFile.C. Fixing instance name containing minus sign

- source/framework/core/inc/TRestHits.h
Warning found on sultan with latest Debian version (12.2) and gcc compiler 12.2.0
The warning is because inheritance of `std::iterator` is deprecated, this PR address this warning is by using declarations inside `TRestHits_Iterator`
> Addressing warning on TResHits_Iterator in latest compiler (12.2.0)

- source/framework/analysis/inc/TRestBenchMarkProcess.h
- source/framework/analysis/inc/TRestDataQualityProcess.h
- source/framework/analysis/inc/TRestEventRateAnalysisProcess.h
- source/framework/analysis/inc/TRestEventSelectionProcess.h
- source/framework/analysis/inc/TRestMySQLToAnalysisProcess.h
- source/framework/analysis/inc/TRestRealTimeAddInputFileProcess.h
- source/framework/analysis/inc/TRestRealTimeDrawingProcess.h
- source/framework/analysis/inc/TRestSummaryProcess.h
- source/framework/core/src/TRestMetadata.cxx
- source/framework/core/src/TRestTask.cxx
- source/framework/tools/inc/TRestReflector.h
Removal of custom `typedef REST_Reflection::TRestReflector any` since it is misleading with `std::any`.
The custom typedef `any` has been replaced by existing `typedef REST_Reflection::TRestReflector RESTValue`
Related PR:
https://github.com/rest-for-physics/detectorlib/pull/100
https://github.com/rest-for-physics/rawlib/pull/121
https://github.com/rest-for-physics/geant4lib/pull/111
https://github.com/rest-for-physics/tracklib/pull/37
https://github.com/rest-for-physics/legacylib/pull/10
https://github.com/rest-for-physics/connectorslib/pull/39
> Removal of custom typedef any since it is misleading with std::any

- source/framework/core/src/TRestMetadata.cxx
Using this update now we will be able to create a template section in the following way.
```
<TRestDataSet name="BabyIAXO_XMM_mm_P${STEP}" />
<parameter name="filePattern" value="${DUST}/run_*rayTracing_Primakoff_XMM_Micromegas_P${STEP}*_V2.4.0.root"/>
...
</TRestDataSet>
```
In that way I can now create datasets for each gas step in BabyIAXO with one single definition.
The new code was tested and working properly when using:
```
restManager GenerateDataSets dataset.rml BabyIAXO_XMM_mm_P991
```
> RML metadata instances will allow now env variables in the name definition.

- source/bin/restManager.cxx
- source/framework/core/src/TRestDataSet.cxx
Adding more output inside `TRestDataSet::GenerateDataSet` to know the state of dataset compilation.
Adding progress bar at the file selection stage
> Increasing default verbose level of `restManager` to `Info`

- source/framework/core/inc/TRestProcessRunner.h
- source/framework/core/src/TRestProcessRunner.cxx
- source/framework/core/src/TRestRun.cxx
`TGeoManager` is now carried over after processing with `restManager`.
> Save geometry after processing

- source/framework/core/inc/TRestMetadata.h
- source/framework/core/src/TRestMetadata.cxx
- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestTools.cxx
Improve support for remote files: when a metadata file is added in the usual way (`addMetadata` element in the xml) if it parses as an http(s) uri it will be downloaded and saved to the local filesystem.
> Improve support for remote metadata files

- source/framework/core/inc/TRestDataSet.h
- source/framework/core/src/TRestDataSet.cxx
Implementation of merging of metadata while importing more than one dataset, in addition any file inside the list which is not a valid dataSet will be skipped.
Address issue #486
> Dataset merge issue

- cmake/thisREST.cmake
See rest-for-physics/geant4lib#116
> Adding CRY to LD_LIBRARY_PATH inside thisREST.sh

- cmake/thisREST.cmake
- macros/REST_CheckValidRuns.C
- macros/REST_GenerateDataSets.C
- source/framework/core/src/TRestSystemOfUnits.cxx
This PR brings the following updates:
- `REST_GenerateDataSets` will now accept to define optionally an output path.
- Added an alias: `restListMacros` to `thisREST.sh` so that users become aware of the possibility to print out a list of macros and their corresponding documentation.
- Added more informative warning on `TRestSystemOfUnits`.
- Renamed `REST_CheckRunFileList` renamed to `REST_CheckValidRuns`. It has also been documented, and a new optional argument `purge` allows to remove the non-valid runs.
> Minor updates 

- cmake/thisREST.cmake
Before this change, `REST_HOME` was set to the user's home at the time of installation, which makes sense if the user is who build and install REST. However this breaks when REST is used on shared systems as the local user would have `REST_HOME` point to the home of the user who installed REST.
> fix: `REST_HOME` is now dynamically set to the user's home

- source/framework/analysis/inc/TRestDataSetOdds.h
- source/framework/analysis/src/TRestDataSetOdds.cxx
This PR is meant to solve a problem when computing log odds for columns of the dataset with int values. This problem happens because the lambda function `GetLogOdds` requires the `double val` parameter,  which causes the TTreeReader to read the corresponding column as it was a double, thus causing error when the branch is not double type. To solve this in a simple way, the RDataFrame  columns (of the selected observables to compute the log odds) that are not double types are Redefine with a static_cast<double> to double. This solves the issue with simple types such as int (which is a common case).
Also some minor additions (see list below).
The changes are:
- Redefine the columns involved in log odds computation to be casted to double.
- Some debug messages are added within the …
> TRestDataSetOdds fix and some more

- source/framework/analysis/inc/TRestDataSetGainMap.h
- source/framework/analysis/src/TRestDataSetGainMap.cxx
Some improvements to the TRestDataSetGainMap:
- [Naming the segmented spectra TH1F](https://github.com/rest-for-physics/framework/commit/3396b55a6d391d4834343c4d15116be65367ac8b). Better practice to name them appropiately.
- [Simplifying some overloads](https://github.com/rest-for-physics/framework/commit/69eefa9e73903aa30c7f6a5e3223305370602766). This avoids explicit casting on parameters of DrawSpectrum, DrawLinearFit and Refit functions when calling them. This simplyfies the procedure of checking and refitting the peaks.
- [Adding function UpdateCalibrationFits()](https://github.com/rest-for-physics/framework/commit/0effbab29c9d8ff180b7cffa208da7919cfb62cf). This is useful to write auxiliar code (macros) that help on the refitting of the peaks.
- Updating and [improving …
> TRestDataSetGainMap improvements

- source/framework/core/src/TRestEvent.cxx
- source/framework/core/src/TRestMetadata.cxx
- source/framework/tools/inc/TRestTools.h
- source/framework/tools/src/TRestTools.cxx
I noticed some analysis processes were failing when running concurrently and this fixes it.
> Add option to PID prefix on downloads to avoid faults

- source/framework/analysis/inc/TRestDataSetGainMap.h
- source/framework/analysis/src/TRestDataSetGainMap.cxx
Bugs fixing:
- TRestDataSetGainMap::Module::DrawSpectrum and DrawLinearFit didnt associate properly the subpad canvas to the corresponding spectrum/linearfit. 
- TRestDataSetGainMap::Module::DrawGainMap had fNumberOfSegmentsX and fNumberOfSegmentsY swapped.
Improvements:
- Description for class attributes and cleaning header comments
- Add cuts to apply to the input calibration TRestDataSet. Printing of the cut was implemented here because the TRestCut::PrintMetadata() does not show the cuts (maybe this should be addressed there instead...)
- Possibility to exclude columns in TRestDatasetGainMap::CalibrateDataSet to exported TRestDataSet
- Add whole module spectrum and calibration. For this, two private methods were added to avoid duplicated code.
> TRestDataSetGainMap improvements and bug fixes

- source/framework/core/inc/TRestDataSetPlot.h
- source/framework/core/src/TRestDataSetPlot.cxx
- Extended the _scale_ option to use any mathematical expression in combination with the special keywords.
New keywords:
- _entries_
- _runLength_
- _integral_
- Add _cuts_, _cutNames_, _panelCut_ and _panelCutNames_ to paramMap to be able to show them in the panel (in the same way as _meanRate_ for example). Also add RESTinfo message to output the global and additional panel cuts applied.
- EnableMultiThreading when handling the TRestDataSet (avoids annoying _"Warning in <ROOT_TImplicitMT_DisableImplicitMT>: Implicit multi-threading is already disabled"_ message)
- Added new key _expression_ in panel definition to parse a mathematical expression that can contain any of the previous key values (variable, metadata and observable). It is a generalization of these previous keys, so this new …
> TRestDataSetPlot improvements

- source/framework/sensitivity/inc/TRestComponent.h
- source/framework/sensitivity/inc/TRestComponentFormula.h
- source/framework/sensitivity/inc/TRestExperiment.h
- source/framework/sensitivity/inc/TRestExperimentList.h
- source/framework/sensitivity/inc/TRestSensitivity.h
- source/framework/sensitivity/src/TRestComponent.cxx
- source/framework/sensitivity/src/TRestComponentFormula.cxx
- source/framework/sensitivity/src/TRestExperiment.cxx
- source/framework/sensitivity/src/TRestExperimentList.cxx
- source/framework/sensitivity/src/TRestSensitivity.cxx
Some fixes I had to add in order to properly calculate the axion helioscope sensitivity in the axionlib PR.
Some new features:
- Now a `TRestComponent` may initialize parameterization nodes using initial/final values and a step. Linear o logarithmic scales are allowed.
- `TRestExperiment::GenerateMockDataSet` might receive a boolean, when it is true, the number of counts of the mock dataset will be generated with the exact average from background, instead of performing a Poissonian MC-distribution.
- Added `fUseAverage` member to `TRestExperimentList` and `TRestExperiment` so that we can enable/disable this feature.
This PR is related to PR https://github.com/rest-for-physics/axionlib/pull/93
> Adding IAXO sensitivity examples and updating sensitivity classes when necessary

- source/framework/core/inc/TRestDataSet.h
- source/framework/core/src/TRestDataSet.cxx
- source/framework/sensitivity/inc/TRestComponentDataSet.h
- source/framework/sensitivity/src/TRestComponentDataSet.cxx
- Added new methods `Range` and `ApplyRange` to `TRestDataSet` they allow to define a sample subset range from the dataset. When we use `ApplyRange` the internal data frame will be updated too. If we only invoke `Range` a `RDF::Node` with the specified range will be returned, but no internal modification will happen.
- Solving an issue in `ExtractParametricNodes` appearing when the dataset is too large, of the order of 1500M entries. The, `fSplitEntries=600,000` divides the operation of node extraction into several steps. See also ROOT-forum entry: https://root-forum.cern.ch/t/problem-with-large-number-of-entries-inside-rdataframe/59632
- `TRestComponentDataSet::fDFRange` data member added. It allows to control the range of the dataset entries that will be used to generate the component. …
> Component and dataset upgrades

- source/framework/analysis/inc/TRestEventSelectionProcess.h
- source/framework/analysis/src/TRestEventSelectionProcess.cxx
Adding new possibility of using the TRestEventSelectionProcess without an external fileWithIDs by evaluating the conditions on the TRestAnalysisTree of the processing file itself.
> TRestEventSelectionProcess upgrade

- source/framework/core/src/startup.cpp
This PR removes an initialization message on startup.cpp
When the python REST library is imported this message is printed. We don't want to spam the stdout on imports which may have unintended consecuences (trying to capture the stdout of a program, etc.).
If we want this message to be displayed perhaps a better place is the dialog after initializing `restRoot`.
> Remove initialization message on startup

- source/framework/core/inc/TRestRun.h
- source/framework/core/src/TRestProcessRunner.cxx
Add method to return run elapsed time.
> TRestRun methods and cleanup

- source/framework/analysis/src/TRestEventRateAnalysisProcess.cxx
- source/framework/analysis/src/TRestEventSelectionProcess.cxx
- source/framework/core/src/TRestProcessRunner.cxx
> Minor variable renaming

- source/framework/core/src/TRestBrowser.cxx
There is a bug when using the macro REST_ViewEvents that didn't allow to select an event by their event ID. I found that is cause by a simple typo in TRestBrowser class. This PR fixes the bug.
> Fix bug when selecting event by ID

- source/framework/analysis/inc/TRestEventTimeSelectionProcess.h
- source/framework/analysis/src/TRestEventTimeSelectionProcess.cxx
Implementation of TRestEventTimeSelectionProcess, a new TRestEventProcess to select the events by their time given a set of active or dead datetime ranges. Although this could be achieved in analysis through cuts to the timeStamp or by using the already existing TRestEventSelectionProcess, this new process will be very useful in the case that the run contains a lot (order of tens or more) of different active/dead time periods, for example, in long background runs with poor detector stability.
> Implementation of TRestEventTimeSelectionProcess to select events by their timeStamp

- source/framework/core/inc/TRestVolumeHits.h
- source/framework/core/src/TRestVolumeHits.cxx
When doing the linearization process of tracks for alpha analysis, the length is always a bit shorter than it should. This is due to the kMeansClustering algorithm that tends to pull the nodes position towards the center of the track. This effect is diminuished by adding more nodes, but this ends up messing the track reconstruction and length resolution. 
To avoid these, we can fix the position of the first and last node to be at the start and end of the track and not be changed during the kMeansClustering algorithm.
> [!IMPORTANT]
> This change is needed for [54](https://github.com/rest-for-physics/tracklib/pull/54).
> Add option to fix the first and last node in kMeansClustering
